apiVersion: v1
kind: LimitRange
metadata:
  annotations:
    toolchain.dev.openshift.com/last-applied-configuration: '{"apiVersion":"v1","kind":"LimitRange","metadata":{"labels":{"toolchain.dev.openshift.com/provider":"codeready-toolchain"},"name":"resource-limits","namespace":"jduimovich-dev"},"spec":{"limits":[{"default":{"cpu":"1000m","memory":"750Mi"},"defaultRequest":{"cpu":"10m","memory":"64Mi"},"type":"Container"}]}}'
  labels:
    toolchain.dev.openshift.com/provider: codeready-toolchain
  name: resource-limits
  namespace: jduimovich-dev
spec:
  limits:
    - default:
        cpu: "1"
        memory: 750Mi
      defaultRequest:
        cpu: 10m
        memory: 64Mi
      type: Container
